import Foundation
import SwiftData
import AppKit

@Observable
final class ClipboardMonitor {
    private var timer: Timer?
    private var lastChangeCount: Int = 0
    private let pasteboard = NSPasteboard.general

    /// Pasteboard types to ignore (passwords, transient data)
    private static let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
    ]

    /// Pasteboard types we capture
    private static let capturedTypes: [NSPasteboard.PasteboardType] = [
        .string,
        .rtf,
        .html,
        .tiff,
        .png,
        .fileURL,
    ]

    var onNewClipboardItem: (([ClipboardItemContent], String?, String?) -> Void)?

    var isRunning: Bool { timer != nil }

    func start() {
        lastChangeCount = pasteboard.changeCount
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            self?.checkForChanges()
        }
        RunLoop.current.add(timer!, forMode: .common)
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func checkForChanges() {
        let currentCount = pasteboard.changeCount
        guard currentCount != lastChangeCount else { return }
        lastChangeCount = currentCount

        guard let items = pasteboard.pasteboardItems, !items.isEmpty else { return }

        // Check for concealed/transient types — skip passwords
        let firstItem = items[0]
        let allTypes = firstItem.types.map(\.rawValue)
        for ignoredType in Self.ignoredTypes {
            if allTypes.contains(ignoredType) { return }
        }

        // Skip Universal Clipboard items to avoid duplicates
        if allTypes.contains("com.apple.is-remote-clipboard") { return }

        // Skip items with only dynamic types
        let meaningfulTypes = allTypes.filter { !$0.hasPrefix("dyn.") }
        guard !meaningfulTypes.isEmpty else { return }

        // Capture content for each supported type
        var contents: [ClipboardItemContent] = []
        for type in Self.capturedTypes {
            if let data = firstItem.data(forType: type) {
                // Skip empty data
                if data.isEmpty { continue }
                // For text, skip whitespace-only
                if type == .string, let str = String(data: data, encoding: .utf8), str.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
                    continue
                }
                contents.append(ClipboardItemContent(type: type.rawValue, value: data))
            }
        }

        guard !contents.isEmpty else { return }

        // Get source app info
        let sourceApp = NSWorkspace.shared.frontmostApplication
        let bundleID = sourceApp?.bundleIdentifier
        let appName = sourceApp?.localizedName

        onNewClipboardItem?(contents, bundleID, appName)
    }
}
