import SwiftUI

struct EmojiCategory: Identifiable {
    let id: String
    let name: String
    let icon: String
    let emojis: [String]
}

/// Keyword map for common emoji search terms.
let emojiKeywords: [String: [String]] = [
    // Smileys
    "😀": ["happy", "smile", "grin"], "😃": ["happy", "smile", "grin"],
    "😄": ["happy", "smile", "laugh"], "😁": ["happy", "grin", "beam"],
    "😆": ["laugh", "happy", "lol"], "😅": ["sweat", "nervous", "laugh"],
    "🤣": ["lol", "rofl", "laugh", "funny"], "😂": ["laugh", "cry", "lol", "funny", "tears"],
    "🙂": ["smile", "ok"], "🙃": ["upside", "sarcasm", "ironic"],
    "😉": ["wink", "flirt"], "😊": ["blush", "happy", "smile", "shy"],
    "😇": ["angel", "innocent", "halo"], "🥰": ["love", "hearts", "adore"],
    "😍": ["love", "heart", "eyes", "crush"], "🤩": ["star", "excited", "wow", "amazing"],
    "😘": ["kiss", "love", "blow"], "😗": ["kiss", "whistle"],
    "😚": ["kiss", "blush"], "😙": ["kiss", "smile"],
    "🥲": ["sad", "smile", "cry", "happy"], "😋": ["yum", "tasty", "delicious", "food"],
    "😛": ["tongue", "silly"], "😜": ["wink", "tongue", "silly", "crazy"],
    "🤪": ["crazy", "wild", "silly", "zany"], "😝": ["tongue", "silly", "gross"],
    "🤑": ["money", "rich", "dollar"], "🤗": ["hug", "love", "warm"],
    "🤭": ["oops", "giggle", "shy"], "🫢": ["oops", "surprise", "shy"],
    "🫣": ["peek", "shy", "cover"], "🤫": ["quiet", "shh", "secret"],
    "🤔": ["think", "hmm", "wonder", "consider"], "🫡": ["salute", "respect", "yes"],
    "🤐": ["quiet", "zip", "secret", "mute"], "🤨": ["skeptical", "doubt", "sus", "suspicious"],
    "😐": ["neutral", "blank", "meh"], "😑": ["blank", "meh", "annoyed"],
    "😶": ["silent", "quiet", "speechless", "mute"], "🫥": ["invisible", "hidden", "dotted"],
    "😏": ["smirk", "sly", "flirt"], "😒": ["unamused", "bored", "meh"],
    "🙄": ["eye roll", "whatever", "annoyed"], "😬": ["awkward", "cringe", "yikes", "grimace"],
    "🤥": ["lie", "pinocchio", "liar"], "😌": ["relieved", "calm", "peaceful"],
    "😔": ["sad", "pensive", "down"], "😪": ["sleepy", "tired"],
    "🤤": ["drool", "hungry", "yum"], "😴": ["sleep", "zzz", "tired", "nap"],
    "😷": ["sick", "mask", "covid", "ill"], "🤒": ["sick", "fever", "ill", "thermometer"],
    "🤕": ["hurt", "injury", "bandage", "ouch"], "🤢": ["sick", "nausea", "gross", "green"],
    "🤮": ["vomit", "sick", "puke", "gross"], "🥵": ["hot", "heat", "sweating"],
    "🥶": ["cold", "freeze", "ice", "freezing"], "🥴": ["drunk", "woozy", "dizzy"],
    "😵": ["dizzy", "dead", "unconscious"], "🤯": ["mind blown", "explode", "shock", "wow"],
    "🤠": ["cowboy", "yeehaw", "hat", "western"], "🥳": ["party", "celebrate", "birthday", "confetti"],
    "🥸": ["disguise", "glasses", "incognito"], "😎": ["cool", "sunglasses", "awesome"],
    "🤓": ["nerd", "geek", "glasses", "smart"], "🧐": ["monocle", "inspect", "curious"],
    "😕": ["confused", "unsure"], "🫤": ["skeptical", "diagonal", "meh"],
    "😟": ["worried", "concerned", "sad"], "🙁": ["sad", "frown", "unhappy"],
    "😮": ["surprise", "oh", "wow"], "😯": ["surprise", "hushed"],
    "😲": ["shock", "surprise", "astonished", "wow"], "😳": ["blush", "embarrassed", "flushed", "surprised"],
    "🥺": ["pleading", "puppy", "cute", "please", "sad"], "🥹": ["grateful", "holding tears", "touched"],
    "😦": ["frown", "open", "surprise"], "😧": ["anguish", "shock"],
    "😨": ["fear", "scared", "afraid"], "😰": ["anxious", "sweat", "nervous", "worried"],
    "😥": ["sad", "relieved", "disappointed"], "😢": ["cry", "sad", "tear"],
    "😭": ["cry", "sob", "sad", "bawl", "tears"], "😱": ["scream", "fear", "shock", "scared", "horror"],
    "😖": ["confounded", "frustrated"], "😣": ["persevere", "struggle"],
    "😞": ["disappointed", "sad", "down"], "😓": ["sweat", "tired", "hard"],
    "😩": ["weary", "tired", "exhausted"], "😫": ["tired", "frustrated", "exhausted"],
    "🥱": ["yawn", "bored", "tired", "sleepy"], "😤": ["angry", "triumph", "huff"],
    "😡": ["angry", "mad", "rage", "furious"], "😠": ["angry", "mad"],
    "🤬": ["swear", "curse", "angry", "mad", "explicit"], "😈": ["devil", "evil", "mischief", "naughty"],
    "👿": ["devil", "angry", "evil"], "💀": ["dead", "skull", "death", "dying"],
    "☠️": ["skull", "danger", "death", "poison"], "💩": ["poop", "poo", "crap", "shit"],
    "🤡": ["clown", "joke", "funny"], "👹": ["ogre", "monster", "demon"],
    "👺": ["goblin", "monster", "tengu"], "👻": ["ghost", "boo", "halloween", "spooky"],
    "👽": ["alien", "ufo", "space", "et"], "👾": ["alien", "space", "invader", "game"],
    "🤖": ["robot", "bot", "machine", "ai"], "😺": ["cat", "happy", "smile"],
    "😸": ["cat", "grin", "smile"], "😹": ["cat", "laugh", "tears"],
    "😻": ["cat", "love", "heart"], "😼": ["cat", "smirk", "wry"],
    "😽": ["cat", "kiss"], "🙀": ["cat", "weary", "shock"],
    "😿": ["cat", "cry", "sad"], "😾": ["cat", "angry", "pout"],
    // Hands & gestures
    "👋": ["wave", "hello", "bye", "hi"], "🤚": ["hand", "stop", "raised"],
    "🖐️": ["hand", "five", "fingers"], "✋": ["hand", "stop", "high five"],
    "🖖": ["vulcan", "spock", "star trek"], "👌": ["ok", "perfect", "nice", "good"],
    "🤌": ["pinch", "italian", "chef kiss"], "🤏": ["small", "tiny", "little", "pinch"],
    "✌️": ["peace", "victory", "two"], "🤞": ["fingers crossed", "luck", "hope"],
    "🤟": ["love", "rock"], "🤘": ["rock", "metal", "horns"],
    "🤙": ["call", "phone", "shaka", "hang loose"], "👈": ["left", "point"],
    "👉": ["right", "point"], "👆": ["up", "point"],
    "🖕": ["middle finger", "fuck", "rude"], "👇": ["down", "point"],
    "☝️": ["up", "point", "one"], "👍": ["thumbs up", "yes", "good", "like", "ok", "approve"],
    "👎": ["thumbs down", "no", "bad", "dislike", "disapprove"], "✊": ["fist", "power", "punch"],
    "👊": ["fist bump", "punch", "bro"], "🤛": ["fist", "left"],
    "🤜": ["fist", "right"], "👏": ["clap", "applause", "bravo"],
    "🙌": ["raise", "hooray", "celebrate", "praise"], "🫶": ["heart hands", "love"],
    "👐": ["open hands", "jazz"], "🤲": ["palms up", "prayer"],
    "🤝": ["handshake", "deal", "agree"], "🙏": ["pray", "please", "thanks", "hope", "namaste"],
    "💪": ["strong", "muscle", "flex", "bicep", "arm", "power"],
    // Hearts & love
    "❤️": ["heart", "love", "red"], "🧡": ["heart", "orange"],
    "💛": ["heart", "yellow"], "💚": ["heart", "green"],
    "💙": ["heart", "blue"], "💜": ["heart", "purple"],
    "🖤": ["heart", "black"], "🤍": ["heart", "white"],
    "🤎": ["heart", "brown"], "💔": ["broken heart", "sad", "heartbreak"],
    "❤️‍🔥": ["heart", "fire", "passion"], "❤️‍🩹": ["heart", "heal", "mend"],
    "💕": ["hearts", "love"], "💗": ["heart", "growing"],
    "💖": ["heart", "sparkle"], "💘": ["heart", "arrow", "cupid"],
    "💝": ["heart", "gift", "ribbon"],
    // Animals
    "🐶": ["dog", "puppy", "pet", "cute"], "🐱": ["cat", "kitten", "pet", "cute"],
    "🐭": ["mouse", "rat"], "🐹": ["hamster", "pet"],
    "🐰": ["rabbit", "bunny", "easter"], "🦊": ["fox", "clever"],
    "🐻": ["bear", "teddy"], "🐼": ["panda", "bear", "cute"],
    "🐨": ["koala", "australia"], "🐯": ["tiger", "cat"],
    "🦁": ["lion", "king", "cat"], "🐮": ["cow", "moo"],
    "🐷": ["pig", "oink"], "🐸": ["frog", "toad", "kermit"],
    "🐵": ["monkey", "ape"], "🐔": ["chicken", "hen", "rooster"],
    "🐧": ["penguin", "arctic", "cold"], "🐦": ["bird", "tweet"],
    "🐍": ["snake", "serpent"], "🐢": ["turtle", "tortoise", "slow"],
    "🐙": ["octopus", "tentacle"], "🐬": ["dolphin", "ocean", "sea"],
    "🐳": ["whale", "ocean", "sea"], "🦈": ["shark", "ocean", "jaws"],
    "🐊": ["crocodile", "alligator"], "🦋": ["butterfly", "insect", "pretty"],
    "🐝": ["bee", "honey", "buzz"], "🐞": ["ladybug", "insect"],
    // Nature
    "🌸": ["cherry blossom", "flower", "spring", "sakura"], "🌹": ["rose", "flower", "love", "red"],
    "🌻": ["sunflower", "flower", "sun"], "🌷": ["tulip", "flower", "spring"],
    "🌲": ["tree", "evergreen", "pine", "christmas"], "🌳": ["tree", "deciduous"],
    "🌴": ["palm", "tree", "tropical", "beach", "island"], "🍀": ["clover", "luck", "lucky", "irish"],
    "🍁": ["maple", "leaf", "fall", "autumn", "canada"],
    // Food
    "🍎": ["apple", "fruit", "red"], "🍕": ["pizza", "food", "cheese"],
    "🍔": ["burger", "hamburger", "food", "fast food"], "🍟": ["fries", "food", "fast food", "french"],
    "🌮": ["taco", "mexican", "food"], "🌯": ["burrito", "wrap", "mexican"],
    "🍣": ["sushi", "japanese", "food", "fish"], "🍜": ["ramen", "noodle", "soup", "japanese"],
    "🍦": ["ice cream", "dessert", "sweet", "cone"], "🍩": ["donut", "doughnut", "sweet", "dessert"],
    "🍪": ["cookie", "sweet", "dessert", "biscuit"], "🎂": ["cake", "birthday", "party", "celebrate"],
    "🍰": ["cake", "shortcake", "dessert", "sweet"], "☕": ["coffee", "tea", "hot", "drink", "cafe"],
    "🍺": ["beer", "drink", "alcohol", "cheers"], "🍷": ["wine", "drink", "alcohol", "glass"],
    "🍾": ["champagne", "celebrate", "party", "bottle"],
    // Symbols
    "⭐": ["star", "favorite"], "🌟": ["star", "sparkle", "glow"],
    "💫": ["dizzy", "star", "magic"], "✨": ["sparkle", "magic", "stars", "shine", "glitter"],
    "⚡": ["lightning", "bolt", "electric", "power", "flash", "zap"],
    "🔥": ["fire", "hot", "flame", "lit"], "💥": ["boom", "explosion", "crash", "bang"],
    "☀️": ["sun", "sunny", "bright", "weather"], "🌈": ["rainbow", "pride", "colorful"],
    "✅": ["check", "yes", "done", "complete", "correct"], "❌": ["no", "wrong", "cross", "delete", "remove"],
    "❗": ["exclamation", "important", "alert", "warning"], "❓": ["question", "what", "help"],
    "💯": ["hundred", "perfect", "score", "100"], "👀": ["eyes", "look", "see", "watch"],
    "🔑": ["key", "lock", "password", "security"], "🔒": ["lock", "secure", "password", "private"],
    "🔓": ["unlock", "open"],
    // Flags (common)
    "🇺🇸": ["usa", "america", "united states", "us"], "🇬🇧": ["uk", "britain", "england", "british"],
    "🇨🇦": ["canada", "canadian"], "🇦🇺": ["australia", "australian"],
    "🇩🇪": ["germany", "german"], "🇫🇷": ["france", "french"],
    "🇪🇸": ["spain", "spanish"], "🇮🇹": ["italy", "italian"],
    "🇯🇵": ["japan", "japanese"], "🇰🇷": ["korea", "korean"],
    "🇨🇳": ["china", "chinese"], "🇮🇳": ["india", "indian"],
    "🇧🇷": ["brazil", "brazilian"], "🇲🇽": ["mexico", "mexican"],
    "🇷🇺": ["russia", "russian"], "🇺🇦": ["ukraine", "ukrainian"],
    // Objects
    "💻": ["computer", "laptop", "mac", "code"], "📱": ["phone", "mobile", "iphone", "cell"],
    "⌨️": ["keyboard", "type", "input"], "🖥️": ["computer", "desktop", "monitor", "screen"],
    "📷": ["camera", "photo", "picture"], "💡": ["lightbulb", "idea", "bright", "lamp"],
    "📝": ["memo", "note", "write", "pencil"], "📚": ["books", "read", "study", "library"],
    "💰": ["money", "bag", "rich", "dollar"], "💵": ["money", "dollar", "cash", "bill"],
    "📧": ["email", "mail", "letter"], "📦": ["package", "box", "delivery", "shipping"],
    // Activities
    "⚽": ["soccer", "football", "sport", "ball"], "🏀": ["basketball", "sport", "ball", "nba"],
    "🏈": ["football", "american", "sport", "nfl"], "⚾": ["baseball", "sport", "ball"],
    "🎾": ["tennis", "sport", "ball"], "🏆": ["trophy", "winner", "champion", "award"],
    "🥇": ["gold", "medal", "first", "winner"], "🎮": ["game", "controller", "gaming", "play", "video game"],
    "🎲": ["dice", "game", "random", "luck"], "🎯": ["target", "bullseye", "goal", "dart"],
    "🎨": ["art", "paint", "palette", "creative"], "🎬": ["movie", "film", "cinema", "action"],
    "🎤": ["microphone", "sing", "karaoke", "music"], "🎧": ["headphones", "music", "listen", "audio"],
    "🎵": ["music", "note", "song"], "🎸": ["guitar", "music", "rock"],
    // Travel
    "🚗": ["car", "drive", "vehicle", "auto"], "✈️": ["plane", "airplane", "flight", "travel"],
    "🚀": ["rocket", "space", "launch", "fast"], "🏠": ["house", "home"],
    "🏢": ["office", "building", "work"], "🗽": ["statue of liberty", "new york", "nyc", "america"],
]

let emojiCategories: [EmojiCategory] = [
    EmojiCategory(id: "recent", name: "Recently Used", icon: "clock", emojis: []),
    EmojiCategory(id: "smileys", name: "Smileys & People", icon: "face.smiling", emojis: [
        "😀", "😃", "😄", "😁", "😆", "😅", "🤣", "😂", "🙂", "🙃",
        "😉", "😊", "😇", "🥰", "😍", "🤩", "😘", "😗", "😚", "😙",
        "🥲", "😋", "😛", "😜", "🤪", "😝", "🤑", "🤗", "🤭", "🫢",
        "🫣", "🤫", "🤔", "🫡", "🤐", "🤨", "😐", "😑", "😶", "🫥",
        "😏", "😒", "🙄", "😬", "🤥", "😌", "😔", "😪", "🤤", "😴",
        "😷", "🤒", "🤕", "🤢", "🤮", "🥵", "🥶", "🥴", "😵", "🤯",
        "🤠", "🥳", "🥸", "😎", "🤓", "🧐", "😕", "🫤", "😟", "🙁",
        "😮", "😯", "😲", "😳", "🥺", "🥹", "😦", "😧", "😨", "😰",
        "😥", "😢", "😭", "😱", "😖", "😣", "😞", "😓", "😩", "😫",
        "🥱", "😤", "😡", "😠", "🤬", "😈", "👿", "💀", "☠️", "💩",
        "🤡", "👹", "👺", "👻", "👽", "👾", "🤖", "😺", "😸", "😹",
        "😻", "😼", "😽", "🙀", "😿", "😾", "👋", "🤚", "🖐️", "✋",
        "🖖", "🫱", "🫲", "🫳", "🫴", "👌", "🤌", "🤏", "✌️", "🤞",
        "🫰", "🤟", "🤘", "🤙", "👈", "👉", "👆", "🖕", "👇", "☝️",
        "🫵", "👍", "👎", "✊", "👊", "🤛", "🤜", "👏", "🙌", "🫶",
        "👐", "🤲", "🤝", "🙏", "💪", "🦾", "🦿", "🦵", "🦶", "👂",
    ]),
    EmojiCategory(id: "animals", name: "Animals & Nature", icon: "hare", emojis: [
        "🐶", "🐱", "🐭", "🐹", "🐰", "🦊", "🐻", "🐼", "🐻‍❄️", "🐨",
        "🐯", "🦁", "🐮", "🐷", "🐸", "🐵", "🙈", "🙉", "🙊", "🐒",
        "🐔", "🐧", "🐦", "🐤", "🐣", "🐥", "🦆", "🦅", "🦉", "🦇",
        "🐺", "🐗", "🐴", "🦄", "🐝", "🪱", "🐛", "🦋", "🐌", "🐞",
        "🐜", "🪰", "🪲", "🪳", "🦟", "🦗", "🕷️", "🕸️", "🦂", "🐢",
        "🐍", "🦎", "🦖", "🦕", "🐙", "🦑", "🦐", "🦞", "🦀", "🪸",
        "🐡", "🐠", "🐟", "🐬", "🐳", "🐋", "🦈", "🐊", "🐅", "🐆",
        "🌸", "💮", "🏵️", "🌹", "🥀", "🌺", "🌻", "🌼", "🌷", "🌱",
        "🪴", "🌲", "🌳", "🌴", "🌵", "🌾", "🌿", "☘️", "🍀", "🍁",
        "🍂", "🍃", "🪺", "🪹",
    ]),
    EmojiCategory(id: "food", name: "Food & Drink", icon: "fork.knife", emojis: [
        "🍇", "🍈", "🍉", "🍊", "🍋", "🍌", "🍍", "🥭", "🍎", "🍏",
        "🍐", "🍑", "🍒", "🍓", "🫐", "🥝", "🍅", "🫒", "🥥", "🥑",
        "🍆", "🥔", "🥕", "🌽", "🌶️", "🫑", "🥒", "🥬", "🥦", "🧄",
        "🧅", "🍄", "🥜", "🫘", "🌰", "🍞", "🥐", "🥖", "🫓", "🥨",
        "🥯", "🥞", "🧇", "🧀", "🍖", "🍗", "🥩", "🥓", "🍔", "🍟",
        "🍕", "🌭", "🥪", "🌮", "🌯", "🫔", "🥙", "🧆", "🥚", "🍳",
        "🥘", "🍲", "🫕", "🥣", "🥗", "🍿", "🧈", "🧂", "🥫", "🍱",
        "🍘", "🍙", "🍚", "🍛", "🍜", "🍝", "🍠", "🍢", "🍣", "🍤",
        "🍥", "🥮", "🍡", "🥟", "🥠", "🥡", "🦀", "🦞", "🦐", "🦑",
        "🍦", "🍧", "🍨", "🍩", "🍪", "🎂", "🍰", "🧁", "🥧", "🍫",
        "🍬", "🍭", "🍮", "🍯", "🍼", "🥛", "☕", "🫖", "🍵", "🍶",
        "🍾", "🍷", "🍸", "🍹", "🍺", "🍻", "🥂", "🥃", "🫗", "🥤",
    ]),
    EmojiCategory(id: "activity", name: "Activity", icon: "sportscourt", emojis: [
        "⚽", "🏀", "🏈", "⚾", "🥎", "🎾", "🏐", "🏉", "🥏", "🎱",
        "🪀", "🏓", "🏸", "🏒", "🏑", "🥍", "🏏", "🪃", "🥅", "⛳",
        "🪁", "🏹", "🎣", "🤿", "🥊", "🥋", "🎽", "🛹", "🛼", "🛷",
        "⛸️", "🥌", "🎿", "⛷️", "🏂", "🪂", "🏋️", "🤸", "🤺", "⛹️",
        "🤾", "🏌️", "🏇", "🧘", "🏄", "🏊", "🤽", "🚣", "🧗", "🚵",
        "🚴", "🏆", "🥇", "🥈", "🥉", "🏅", "🎖️", "🏵️", "🎗️", "🎫",
        "🎟️", "🎪", "🎭", "🎨", "🎬", "🎤", "🎧", "🎼", "🎹", "🥁",
        "🪘", "🎷", "🎺", "🪗", "🎸", "🪕", "🎻", "🎲", "♟️", "🎯",
        "🎳", "🎮", "🎰", "🧩",
    ]),
    EmojiCategory(id: "travel", name: "Travel & Places", icon: "car", emojis: [
        "🚗", "🚕", "🚙", "🚌", "🚎", "🏎️", "🚓", "🚑", "🚒", "🚐",
        "🛻", "🚚", "🚛", "🚜", "🏍️", "🛵", "🛺", "🚲", "🛴", "🚏",
        "🛣️", "🛤️", "⛽", "🛞", "🚨", "🚥", "🚦", "🛑", "🚧", "⚓",
        "🛟", "⛵", "🚤", "🛳️", "⛴️", "🛥️", "🚢", "✈️", "🛩️", "🛫",
        "🛬", "🪂", "💺", "🚁", "🚟", "🚠", "🚡", "🛰️", "🚀", "🛸",
        "🏠", "🏡", "🏢", "🏣", "🏤", "🏥", "🏦", "🏨", "🏩", "🏪",
        "🏫", "🏬", "🏭", "🏯", "🏰", "💒", "🗼", "🗽", "⛪", "🕌",
        "🛕", "🕍", "⛩️", "🕋", "⛲", "⛺", "🌁", "🌃", "🏙️", "🌄",
        "🌅", "🌆", "🌇", "🌉", "🗾", "🏔️", "⛰️", "🌋", "🗻", "🏕️",
    ]),
    EmojiCategory(id: "objects", name: "Objects", icon: "lightbulb", emojis: [
        "⌚", "📱", "📲", "💻", "⌨️", "🖥️", "🖨️", "🖱️", "🖲️", "💽",
        "💾", "💿", "📀", "🧮", "🎥", "🎞️", "📽️", "📺", "📷", "📸",
        "📹", "📼", "🔍", "🔎", "🕯️", "💡", "🔦", "🏮", "🪔", "📔",
        "📕", "📖", "📗", "📘", "📙", "📚", "📓", "📒", "📃", "📜",
        "📄", "📰", "🗞️", "📑", "🔖", "🏷️", "💰", "🪙", "💴", "💵",
        "💶", "💷", "💸", "💳", "🧾", "💹", "✉️", "📧", "📨", "📩",
        "📤", "📥", "📦", "📫", "📪", "📬", "📭", "📮", "🗳️", "✏️",
        "✒️", "🖋️", "🖊️", "🖌️", "🖍️", "📝", "📁", "📂", "🗂️", "📅",
        "📆", "🗒️", "🗓️", "📇", "📈", "📉", "📊", "📋", "📌", "📍",
        "📎", "🖇️", "📏", "📐", "✂️", "🗃️", "🗄️", "🗑️",
    ]),
    EmojiCategory(id: "symbols", name: "Symbols", icon: "heart", emojis: [
        "❤️", "🧡", "💛", "💚", "💙", "💜", "🖤", "🤍", "🤎", "💔",
        "❤️‍🔥", "❤️‍🩹", "❣️", "💕", "💞", "💓", "💗", "💖", "💘", "💝",
        "⭐", "🌟", "💫", "✨", "⚡", "🔥", "💥", "☀️", "🌈", "☁️",
        "❄️", "💧", "🌊", "✅", "❌", "⭕", "❗", "❓", "❕", "❔",
        "💯", "🔴", "🟠", "🟡", "🟢", "🔵", "🟣", "⚫", "⚪", "🟤",
        "🔶", "🔷", "🔸", "🔹", "🔺", "🔻", "💠", "🔘", "🔳", "🔲",
        "🏁", "🚩", "🎌", "🏴", "🏳️", "🏳️‍🌈", "🏳️‍⚧️", "🏴‍☠️",
        "➕", "➖", "✖️", "➗", "♾️", "💲", "💱", "™️", "©️", "®️",
        "〰️", "➰", "➿", "🔚", "🔙", "🔛", "🔝", "🔜", "✔️", "☑️",
        "🔃", "🔄", "ℹ️", "🔤", "🔡", "🔠", "🆎", "🆑", "🆒", "🆓",
        "🆔", "🆕", "🆖", "🆗", "🆘", "🆙", "🆚", "🈁", "🈂️", "🔑",
        "🗝️", "🔒", "🔓", "🔏", "🔐",
    ]),
    EmojiCategory(id: "flags", name: "Flags", icon: "flag", emojis: [
        "🇺🇸", "🇬🇧", "🇨🇦", "🇦🇺", "🇩🇪", "🇫🇷", "🇪🇸", "🇮🇹", "🇯🇵", "🇰🇷",
        "🇨🇳", "🇮🇳", "🇧🇷", "🇲🇽", "🇷🇺", "🇿🇦", "🇳🇿", "🇮🇪", "🇳🇱", "🇸🇪",
        "🇳🇴", "🇩🇰", "🇫🇮", "🇵🇱", "🇹🇷", "🇸🇦", "🇦🇪", "🇮🇱", "🇪🇬", "🇳🇬",
        "🇰🇪", "🇬🇭", "🇦🇷", "🇨🇱", "🇨🇴", "🇵🇪", "🇻🇪", "🇨🇺", "🇵🇷", "🇯🇲",
        "🇹🇭", "🇻🇳", "🇵🇭", "🇮🇩", "🇲🇾", "🇸🇬", "🇭🇰", "🇹🇼", "🇵🇰", "🇧🇩",
        "🇺🇦", "🇵🇹", "🇬🇷", "🇨🇭", "🇦🇹", "🇧🇪", "🇨🇿", "🇷🇴", "🇭🇺",
    ]),
]
